# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Tensor.trade Python SDK
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  logo: logo.svg

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            show_bases: false
            heading_level: 3