[tool.ariadne-codegen]
schema_path = "resources/schema.graphql"
queries_path = "resources/ariadne_client_configs/collection_data.graphql"
async_client = false
plugins = ["resources.no_reimports.NoReimportsPlugin"]
target_package_path = "tensortradesdk"
target_package_name = "clients"
client_name = "CollectionDataClient"
client_file_name = "collection_data_client"