[tool.ariadne-codegen]
# common
schema_path = "resources/schema.graphql"
plugins = ["resources.no_reimports.NoReimportsPlugin", "resources.docstrings.DocstringsPlugin"]
target_package_path = "tensortradesdk"
base_client_name = "BaseClient"
base_client_file_path = "resources/base_client.py"
# specific
async_client = false
target_package_name = "clients"
queries_path = "resources/ariadne_client_configs/market_data.graphql"
client_name = "MarketDataClient"
client_file_name = "market_data_client"