[tool.ariadne-codegen]
# common
schema_path = "resources/schema.graphql"
plugins = ["resources.no_reimports.NoReimportsPlugin"]
target_package_path = "tensortradesdk"
base_client_name = "BaseClient"
base_client_file_path = "resources/base_client.py"
# specific
async_client = false
target_package_name = "clients"
queries_path = "resources/ariadne_client_configs/transactions.graphql"
client_name = "TransactionsClient"
client_file_name = "transactions_client"