name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # run once every day
    - cron: "0 3 * * *"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: |
        poetry install
    - name: Run tests
      run: |
        poetry run update_gql_schema
    - name: Check GrapqhQL schema changes
      id: schema-changes
      run: |
        if git diff --name-only | grep -q 'resources/schema.graphql'; then
          echo "SCHEMA_CHANGED=true" >> "$GITHUB_OUTPUT"
        else
          echo "SCHEMA_CHANGED=false" >> "$GITHUB_OUTPUT"
        fi
        echo "SCHEMA_CHANGED=true" >> "$GITHUB_OUTPUT"
    - name: Run integration tests on schema changes
      if: ${{ steps.schema-changes.outputs.SCHEMA_CHANGED == 'true' }}
      env:
        TENSOR_API_KEY: ${{ secrets.TENSOR_API_KEY }}
      run: |
        echo $TENSOR_API_KEY
        poetry run pytest tests/integration
        
        
